[versions]
netty = "4.2.17.Final"
junit = "5.14.1"
webrtc-java = "0.17.0-sm.1"
gson = "2.14.0"
jose4j = "0.9.6"
slf4j = "2.0.19"

[libraries]
expiringmap = { group = "net.jodah", name = "expiringmap", version = "0.5.11" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
netty-bom = { group = "io.netty", name = "netty-bom", version.ref = "netty" }
netty-common = { group = "io.netty", name = "netty-common" }
netty-buffer = { group = "io.netty", name = "netty-buffer" }
netty-codec-base = { group = "io.netty", name = "netty-codec-base" }
netty-codec-http = { group = "io.netty", name = "netty-codec-http" }
netty-codec-haproxy = { group = "io.netty", name = "netty-codec-haproxy" }
netty-transport = { group = "io.netty", name = "netty-transport" }
netty-transport-native-unix-common = { group = "io.netty", name = "netty-transport-native-unix-common" }
webrtc-java = { group = "io.github.sendablemetatype.webrtc", name = "webrtc-java", version.ref = "webrtc-java" }
jose4j = { group = "org.bitbucket.b_c", name = "jose4j", version.ref = "jose4j" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
errorprone-annotations = { group = "com.google.errorprone", name = "error_prone_annotations", version = "2.50.0" }

# Test dependencies
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
jspecify = { group = "org.jspecify", name = "jspecify", version = "1.0.1" }
slf4j-jdk14 = { group = "org.slf4j", name = "slf4j-jdk14", version.ref = "slf4j" }



[bundles]
netty = [ "netty-common", "netty-buffer", "netty-codec-base", "netty-transport", "netty-transport-native-unix-common" ]
junit = [ "junit-jupiter-engine", "junit-jupiter-api", "junit-jupiter-params" ]


