name: Deploy Feature Snapshot

on:
  workflow_dispatch:
    inputs:
      publish-version:
        description: 'Maven snapshot version to publish for this branch'
        required: true
        default: '1.0.0.CR3-bedrock-guard-SNAPSHOT'
        type: string

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      deploy-url: "https://repo.opencollab.dev/maven-snapshots/"
      publish-version: ${{ inputs.publish-version }}
    secrets:
      DEPLOY_USERNAME: ${{ secrets.OPENCOLLAB_USERNAME }}
      DEPLOY_PASSWORD: ${{ secrets.OPENCOLLAB_PASSWORD }}
      PGP_SECRET: ${{ secrets.MAVEN_CENTRAL_SECRET }}
      PGP_PASSPHRASE: ${{ secrets.MAVEN_CENTRAL_PASSPHRASE }}
